# Beginner Python Programming Problems

This document contains a set of programming problems designed for beginners to practice fundamental Python concepts. The problems are structured to build upon each other, with each topic focusing on a specific area of the language. The exercises are all related to a common operational theme to provide a consistent and practical context.


## 1. Basics of Python Using Strings

These problems focus on string manipulation, a fundamental skill in any programming language. You will practice creating, combining, and formatting text strings to generate simple messages and labels.

### Greeting Message

Create a variable `customer_name` with the value "Priya". Print a personalized greeting message: "Hello, Priya! Welcome."

In [5]:
customer_name="Priya"
print(f" Hello,{customer_name}! Welcome." )

 Hello,Priya! Welcome.


### Item Label

Create two variables: `item_name` with "Mango Blast" and `price_per_item` with 80. Print a formatted label showing both pieces of information: "Item: Mango Blast, Price: 80 INR".

In [9]:
item_name="Mango Blast" 
price_per_item =80
print(f"Item:{item_name},Price:{price_per_item}")


Item:Mango Blast,Price:80


### Order Summary

Create variables `item1` ("Vanilla Delight"), `item2` ("Chocolate Chip"), and `total_cost` (300). Print a summary line: "Order: Vanilla Delight, Chocolate Chip. Total: 300 INR."

In [11]:
item1="Vanilla"
item2="Chocolate chip"
total_cost=300
print(f"Order:{item1},{item2}.Total:{total_cost}INR.")

Order:Vanilla,Chocolate chip.Total:300INR.


### Dynamic Message

Create variables `staff_name` ("Arjun") and `current_time` ("10:00 AM"). Print a message announcing the staff member on duty: "Current staff member on duty: Arjun. Time: 10:00 AM."

In [2]:
staff_name="Arjun"
current_time="10:00 AM"
print(f"Current staff member on duty:{staff_name}.Time:{current_time}.")

Current staff member on duty:Arjun.Time:10:00 AM.


### String Length

Find and print the length of the string "Strawberry Sensation".

In [3]:
String="Strawberry Sensation"
print(f"length of the string:{len(String)}")

length of the string:20


### Capitalization

Create a variable `flavor_name` with "butterscotch crunch". Print the flavor name with the first letter of each word capitalized.

In [6]:
flavor_name="butterscotch crunch"
print(flavor_name.title())

Butterscotch Crunch


### Finding Substrings

Check if the word "Milk" is present in the ingredient list string "Milk, Cream, Sugar, Vanilla". Print `True` or `False` based on the result.

In [4]:
ingredient_list="Milk,Cream,Sugar,Vanilla"
print("Milk" in ingredient_list)

True
 Milk in Ingredient:True


### Replacing Text

In the string "The order is for Rahul. Total amount: 250 INR.", replace the name "Rahul" with "Sneha". Print the new string.

In [16]:
String1="The order is for Rahul.Total amount:250 INR."
String2=String1.replace("Rahul","Sneha")
print(String2)

The order is for Sneha.Total amount:250 INR.


### Trimming Whitespace

Remove any leading or trailing spaces from the string "    Chocolate Fudge    " and print the cleaned string.

In [22]:
Flavor=" Chocolate Fudge "
Flavor.strip()

'Chocolate Fudge'

### Splitting a String

Split the string "Monday,Tuesday,Wednesday" by the comma and print the resulting list of days.

In [26]:
days="Monday,Tuesday,Wednesday"
resulting_list_of_days=days.split(",")
print(resulting_list_of_days)

['Monday', 'Tuesday', 'Wednesday']


### Joining a List

Join the list of ingredients `['Milk', 'Sugar', 'Cream']` into a single string separated by hyphens: "Milk-Sugar-Cream".

In [37]:
ingredients=['Milk','Sugar','Cream']
list_of_ingredients="-".join(ingredients)
print(list_of_ingredients)

Milk-Sugar-Cream


### Formatted Receipt Line

Use an f-string to print a receipt line for an item. The item is "Pista" and the price is 120 INR. The output should be "Item: Pista, Price: 120.00 INR".

In [36]:
item="Pista"
price=120 
print(f"Item:{item},Price:{price:.2f} INR.")

Item:Pista,Price:120.00 INR.


### Multi-line String

Create a multi-line string that holds an address: "Shop No. 5, Main Road, City Center". Print this string.

In [47]:
adress="""Shop No.5,
Main Road,
City Center"""
print(adress)

Shop No.5,
Main Road,
City Center


### String Reversal

Take the string "Daily Report" and print it in reverse order.

In [41]:
String="Daily Report"
print(f"Reversed order of the given string :{String[::-1]}")


Reversed order of the given string :tropeR yliaD


### Character Counting

Count the number of times the letter 'a' appears in the string "Banana Caramel".

In [46]:
Flavor="Banana Caramel"
Flavor.count("a")

5

## 2. Flow Control Blocks - if/else and loops

These problems introduce the use of conditional statements and loops to control the flow of a program. You will make decisions based on certain conditions and repeat actions for multiple items.

### Single Condition Check

Create a variable `current_stock` with the value 50. If `current_stock` is less than 20, print "Low stock warning."

In [48]:
current_stock=50
if current_stock<20:
    print("Low stock Warning")
print("Stock check completed")

Stock check completed


### Basic if/else

Create a variable `order_status` with "Pending". If the status is "Pending", print "Order is being prepared.". Otherwise, print "Order is complete."

In [51]:
order_status="Pending"
if order_status=="Pending":
    print("Order is being prepared")
else:
    print("Order is complete")



Order is being prepared


### Multiple Conditions with elif

Create a variable `temperature` with 25. If the temperature is above 30, print "High ambient temperature.". If it's between 20 and 30 (inclusive), print "Normal operating temperature.". Otherwise, print "Low ambient temperature."

In [55]:
temperature=25
if temperature>30:
    print("High ambient temperature")
elif 20<=temperature<=30:
    print("Normal operating temperature")
else:
    print("Low ambient temperature")

Normal operating temperature


### Price-based Discount

A customer's total bill is 550 INR. If the total is over 500 INR, a 10% discount is applied. Calculate and print the final amount. Otherwise, print the original total.

In [60]:
Customer_total_bill=550
if Customer_total_bill>=500:
    print("10% discount applied")
    final_amount=Customer_total_bill*0.9
else:
    print("No Discount applies")
    final_amount=Customer_total_bill
print(f"Final amount:{int(final_amount)} INR")

10% discount applied
Final amount:495 INR


### For Loop: Iterating over a list

Print each item from the list of flavors: `['Vanilla', 'Chocolate', 'Strawberry']`.

In [61]:
flavors=['Vanilla','Chocolate','Strawberry']
for flavor in flavors:
    print(flavor)

Vanilla
Chocolate
Strawberry


### For Loop with a condition

Iterate through the list of flavors `['Vanilla', 'Chocolate', 'Strawberry', 'Mango']`. Print only the flavors that are not 'Strawberry'.

In [67]:
flavors=['Vanilla','Chocolate','Strawberry','Mango']
for flavor in flavors:
    if flavor!="Strawberry":
        print(flavor)

Vanilla
Chocolate
Mango


### While Loop for a Countdown

Simulate a timer for a process that takes 5 minutes. Start a variable `timer` at 5 and print a message each time it decreases, until it reaches 0. E.g., "5 minutes remaining...", "4 minutes remaining...", etc.

In [2]:
timer=5
while timer>=0:
    print(f"{timer} minutes remaining...")
    timer-=1

5 minutes remaining...
4 minutes remaining...
3 minutes remaining...
2 minutes remaining...
1 minutes remaining...
0 minutes remaining...


### Nested Loop

You have a list of flavors `['Vanilla', 'Chocolate']` and a list of toppings `['Sprinkles', 'Nuts']`. Use nested loops to print all possible combinations of a flavor with a topping.

In [4]:
flavors=['Vanilla','Chocolate']
toppings=['Sprinkles','Nuts']
for flavor in flavors:
    for topping in toppings:
        print(f"{flavor} with {topping}")


Vanilla with Sprinkles
Vanilla with Nuts
Chocolate with Sprinkles
Chocolate with Nuts


### Checking for an Empty List

Create a list `daily_tasks = []`. Write a condition that checks if the list is empty. If it is, print "No new tasks for today."

In [7]:
daily_tasks=[]
if not daily_tasks:
    print("No new tasks for today.")

No new tasks for today.


### Using 'break' in a loop

Iterate through a list of daily revenue figures `[12000, 15000, 9000, 18000, 20000]`. Stop and print a message when the revenue for a day falls below 10000 INR.

In [12]:
daily_revenue=[12000,15000,9000,18000,20000]
for revenue in daily_revenue:
    if revenue<10000:
        print(f" Revenue for a day falls below 10000 INR:{revenue}")
        break
    print(f"Revenue is :{revenue}")


Revenue is :12000
Revenue is :15000
 Revenue for a day falls below 10000 INR:9000


### Using 'continue' in a loop

Iterate through a list of production batches `['Batch-A', 'Batch-B', 'Batch-C']`. If a batch name is 'Batch-B', skip the rest of the loop for that iteration and just print "Skipping quality check for Batch-B." For others, print "Running quality check for [Batch Name]".

In [16]:
production_batches=['Batch-A','Batch-B','Batch-C']
for batch in production_batches:
    if batch=="Batch-B":
        print("Skipping quality check for Batch-B")
        continue
    print(f"Running quality check for {batch}")

Running quality check for Batch-A
Skipping quality check for Batch-B
Running quality check for Batch-C


### Combining conditions

An employee, Rohan, has worked 9 hours. His shift is from 9 AM to 6 PM, which is a total of 9 hours. Write a condition that checks if his hours worked are equal to 9 and the current time is after 6 PM. If both are true, print "Rohan's shift is complete."

In [3]:
Employee_name="Rohan"
Working_hours= 9
current_time=19 #24-hour format means 7pm
if Working_hours==9 and current_time>18:
    print(f"{Employee_name}'s shift is complete")


Rohan's shift is complete


### Finding the maximum value in a list

Iterate through a list of daily sales `[8500, 9200, 7800, 11500, 10200]` and find the highest sale amount. Print the result.

In [19]:
daily_sales=[8500,9200,7800,11500,10200]
print(f"highest sale amount:{max(daily_sales)}")

highest sale amount:11500


### Counting items with a condition

You have a list of customer feedback scores `[5, 4, 5, 3, 5, 5, 2]`. Count how many customers gave a rating of 5. Print the count.

In [9]:
feedback_scores=[5,4,5,3,5,5,2]
rating=feedback_scores.count(5)
print(f"customers gave a rating of 5 is {rating}")

customers gave a rating of 5 is 4


### Simulating a process with a loop

A machine takes 10 seconds to make a batch. Simulate this process using a loop that counts down from 10 to 1, printing the remaining time at each step. End with "Process complete."

In [13]:
import time
batch_time=10
while batch_time>0:
    print(f"{batch_time} seconds")
    time.sleep(1)
    batch_time-=1
print("process complete")

10 seconds
9 seconds
8 seconds
7 seconds
6 seconds
5 seconds
4 seconds
3 seconds
2 seconds
1 seconds
process complete


## 3. Reading data from command line using input() functions

These problems focus on getting input from the user. The `input()` function allows your program to be interactive, taking data that the user types in and using it for further processing.

### Simple String Input

Ask the user for their name and then print a greeting message that includes their name.

In [1]:
user_name=input("Enter your name:")
print(f" hello {user_name}")

Enter your name: Fahimida


 hello Fahimida


### Input with a prompt

Ask the user, "What is today's special flavor?" and store the response in a variable. Print the user's response to confirm.

In [2]:
user=input("What is today's special flavor?")
print(f"Today's special flavor is:{user}")

What is today's special flavor? Butter Scotch


Today's special flavor is:Butter Scotch


### Converting input to a number (integer)

Ask the user for the number of scoops they want. Convert the input to an integer and print a confirmation message, e.g., "You ordered 3 scoops."

In [6]:
no_of_scoops=input("Enter the number of scoops:")
user=int(no_of_scoops)
print(f"You ordered {no_of_scoops} scoops")

Enter the number of scoops: 3


You ordered 3 scoops


### Converting input to a number (float)

Ask the user for the total price of their purchase. Convert the input to a floating-point number and print the total with two decimal places, e.g., "Your total is 125.50 INR."

In [10]:
total_price=input("Enter the total price of the purchase:")
user_purchase=float(total_price)
print(f"Your total is {user_purchase:.2f} INR")

Enter the total price of the purchase: 125


Your total is 125.00 INR


### Basic Calculation with User Input

Ask for the number of scoops and the price per scoop (e.g., 80 INR). Calculate and print the total cost.

In [17]:
number_of_scoops=int(input("Enter the number of scoops:"))
price_per_scoop=int(input("Price per scoop:"))
total_cost=number_of_scoops*price_per_scoop
print(f"total_cost of scoops:{total_cost}")

Enter the number of scoops: 3
Price per scoop: 50


total_cost of scoops:150


### Input for a conditional check

Ask the user for a password. If the password is "password123", print "Access granted." Otherwise, print "Access denied."

In [19]:
user_password=input("Enter the password:")
if user_password=="password123":
    print("Access granted")
else:
    print("Access denied")

Enter the password: password123


Access granted


### Input for a loop

Ask the user how many items they want to add to their order. Use a loop to repeatedly ask for the name of an item that many times, and then print a final message confirming the number of items added.

In [26]:
order_items=int(input("number of items add to their order:"))
for item in range(order_items):
    name_of_item=input(f"name of an item{item+1}:")
print(f"number of items added:{order_items}")

number of items add to their order: 4
name of an item1: Vanilla
name of an item2: Chocolate
name of an item3: ButterSCotch
name of an item4: Pista


number of items added:4


### Handling potential errors with input

Ask the user for their age. Write a program that can handle non-numeric input gracefully by printing an error message like "Invalid input. Please enter a number." (Hint: Use a `try-except` block).

In [37]:

try:
    user_age=int(input("Enter the age:"))
    print(f"user_age:{user_age}")
except ValueError as e:
    print("Invalid input.Please enter a number.")

Enter the age: a


Invalid input.Please enter a number.


### Multiple inputs for a transaction

Ask for the customer's name, the item they purchased, and the total amount. Print a complete transaction summary on a single line, e.g., "Transaction for: Anjali, Item: Mango, Amount: 150 INR."

In [27]:
Customer_name=input("Enter the Customer_name:")
item_purchased=input("Enter the item purchased:")
total_amount=input("Enter the total amount:")
print(f"Transaction for:{Customer_name},Item:{item_purchased},Amount:{total_amount} INR")
                    

Enter the Customer_name: Fahimida
Enter the item purchased: Mango
Enter the total amount: 150


Transaction for:Fahimida,Item:Mango,Amount:150 INR


### Using input for a simple menu

Display a menu: "1. View Menu, 2. Place Order, 3. Exit". Ask the user to enter a number and then print a message based on their choice (e.g., "You chose to place an order.").

In [41]:
print("Menu")
print("1.View Menu")
print("2.Place Order")
print("3.Exit")
choice=int(input("Enter a number:"))
if choice==1:
    print("You choose to view menu")
elif choice==2:
    print("You choose to place order")
elif choice==3:
    print("You choose to exit")
else:
     print("inavalid choce")
    

Menu
1.View Menu
2.Place Order
3.Exit


Enter a number: 2


You choose to place order


### Input and string concatenation

Ask for the customer's first name and last name separately. Combine them and print their full name.

In [40]:
first_name=input("Enter the first name:")
last_name=input("Enter the last name:")
Customer_name=first_name+" "+last_name
print(f"fullname:{Customer_name}")

Enter the first name: Fahimida
Enter the last name: Begum


fullname:Fahimida Begum


### Input to check stock

Ask the user for an ingredient name. If the ingredient is "Milk", print "Stock is available." Otherwise, print "Ingredient not in stock."

In [29]:
ingredient_name=input("Enter the ingredient name:")
if ingredient_name=="Milk":
    print("Stock is avialable")
else:
    print("Ingredient not in stock")



Enter the ingredient name: Milk


Stock is avialable


### Input to update a value

A variable `daily_target` is 50. Ask the user for the number of items sold today. If the sales number is greater than or equal to the target, print "Daily target met!"

In [31]:
daily_target=50
number_of_items_sold=int(input("number of items sold today:"))
if number_of_items_sold>=daily_target:
    print("Daily target met!")

number of items sold today: 55


Daily target met!


### Input to control a `while` loop

Ask the user for input. The program should continue to ask for input until the user types "exit".

In [44]:
while True:
    user_input=input("Enter the input:")
    if user_input=="exit":
        print("Loop ended")
        break
    else:
        print(f"You entered :{user_input}")

Enter the input: hlo


You entered :hlo


Enter the input: exit


Loop ended


### Password verification with a loop

Ask the user for a password. If it is incorrect, tell them and ask again. The loop should stop only when the correct password is entered. The correct password is "admin".

In [43]:
correct_password="admin"
while True:
    user_password=input("Enter the password:")
    if user_password==correct_password:
        print("Acess granted")
        break
    else:
        print("Incorrect password! Try Again")

Enter the password: user


Incorrect password! Try Again


Enter the password: abc


Incorrect password! Try Again


Enter the password: admin


Acess granted


## 4. Functions and arguments, global vs local variables

Functions are reusable blocks of code that perform a specific task. These problems will help you define and call functions, pass arguments to them, and understand the difference between local and global variables.

### Simple Function without arguments

Define a function named `welcome_message` that simply prints "Welcome to our store!" Call this function.

In [45]:
def welcome_message():
    print("Welcome to our store!")
welcome_message()

Welcome to our store!


### Function with one argument

Define a function `greet_customer` that takes one argument, `name`. Inside the function, print "Hello, [name]! What can I get for you?". Call this function with the name "Rohan".

In [48]:
def greet_customer(name):
    print(f"Hello,{name}! What can I get for you?")

greet_customer("Rohan")

Hello,Rohan! What can I get for you?


### Function with multiple arguments

Define a function `calculate_total` that takes two arguments, `price` and `quantity`. It should print the total cost. Call the function with `price=100` and `quantity=2`.

In [51]:
def calculate_total(price,quantity):
    total_cost=price*quantity
    print(f"Total_cost:{total_cost}")
calculate_total(100,2)

Total_cost:200


### Function that returns a value

Define a function `get_discounted_price` that takes a `price` and `discount_percentage` as arguments. The function should calculate and return the discounted price. Call the function with `price=500` and `discount_percentage=10`, and print the returned value.

In [56]:
def get_discounted_price(price,discount_percentage):
    print("10% discount applied")
    total_price=price*discount_percentage
    return total_price

get_discounted_price(500,0.9) 

10% discount applied


450.0

### Global vs Local Variable Scope

Create a global variable `shop_name` with the value "Sweet Treats". Define a function `print_shop_name` that tries to access and print this global variable. Also, inside the function, create a local variable `staff_name` with "Pooja" and print it. What happens if you try to print `staff_name` outside the function?

In [83]:
shop_name="Sweet Treats"
def print_shop_name():
    #Local variable
    staff_name="Pooja"
    #Acess global variable
    print(f"shop name={shop_name}")
#print(f"staff name={staff_name}")
print_shop_name()
#Try to print the local variable outside the function
try:
    print(f"staff name={staff_name}")
except NameError as e:
    print(f"Error:{e}")



shop name=Sweet Treats
Error:name 'staff_name' is not defined


### Default argument values

Define a function `serve_order` that takes `customer_name` and an optional `item` argument with a default value of "Classic Vanilla". If the `item` is not provided, the function should use the default. Call the function in two ways: once with just the name "Amit", and once with "Anjali" and the item "Mango Delight".

In [62]:
def serve_order(customer_name,item="Classic Vanilla"):
    print(f"Customer Name:{customer_name},Item:{item}")
#call with default item
serve_order("Amit")
#call with name and item
serve_order("Anjali ","Mango Delight")

Customer Name:Amit,Item:Classic Vanilla
Customer Name:Anjali ,Item:Mango Delight


### Keyword arguments

Define a function `create_receipt_line` that takes `item`, `quantity`, and `price` as arguments. Call the function using keyword arguments, for example: `create_receipt_line(item="Chocolate", quantity=3, price=90)`. This makes the function call more readable.

In [67]:
def create_receipt_line(item,quantity,price):
    print(f"Item={item},Quantity={quantity},price={price}")
create_receipt_line(item="Chocolate",quantity=3,price=90)

Item=Chocolate,Quantity=3,price=90


### Combining loops and functions

Create a function `process_orders` that takes a list of orders. Each order is a string like "Anjali - Vanilla". The function should loop through the list and print a personalized message for each order. Use this function with a sample list of orders.

In [6]:
def process_orders():
    orders=["Anjali-Vanilla","Fahimida-ButterScotch","Tharuni-Chocolate"]
    for order in orders:
        name,flavor=order.split("-")
        print(f"Hello {name} and you ordered flavor:{flavor}")
process_orders()

Hello Anjali and you ordered flavor:Vanilla
Hello Fahimida and you ordered flavor:ButterScotch
Hello Tharuni and you ordered flavor:Chocolate


### Returning multiple values

Define a function `get_stock_info` that returns the `stock_level` (integer) and `last_updated_date` (string). Call the function and unpack the two returned values into separate variables. Print both.

In [8]:
def get_stock_info():
    stock_level=100
    last_updated_date="10-08-2025"
    return stock_level,last_updated_date
#Unpacking values
stock,date=get_stock_info()
print(f"Stock is :{stock}")
print(f"Date is:{date}")

Stock is :100
Date is:10-08-2025


### Function to check a condition

Define a function `check_for_promo` that takes a `total_bill`. If the total is over 1000 INR, the function should return `True`. Otherwise, it should return `False`. Use this function with an if statement to print "Promo applied" or "No promo."

In [2]:
def check_for_promo(total_bill):
    if total_bill>=1000:
        print("Promo applied")
        return True
    else:
        print("No promo")
        return False
check_for_promo(1200)

Promo applied


True

### Function with a list argument

Define a function `print_menu` that takes a list of menu items. The function should loop through the list and print each item with a bullet point.

In [33]:
def print_menu():
    for item in items:
        print(f"- {item}")
items=["Vanilla","Chocolate","ButterScotch"]
print_menu()

-Vanilla
-Chocolate
-ButterScotch


### Modifying a global variable (carefully)

Declare a global variable `total_sales_count = 0`. Define a function `record_sale` that increments this variable by 1. Call this function a few times and then print the final `total_sales_count` to show it has been updated.

In [12]:
total_sales_count=0
def record_sale():
    global total_sales_count
    total_sales_count+=1
#Calling the fuction
record_sale()
record_sale()
record_sale()
record_sale()
print(f"Total_sales_count:{total_sales_count}")

Total_sales_count:4


### Function with variable number of arguments (`*args`)

Define a function `calculate_order_sum` that accepts any number of prices as arguments. The function should sum all the prices and print the total. Call it with a few different sets of prices.

In [80]:
def calculate_order_sum(*price):
    total=sum(price)
    print(f"Total Price:{total}")
calculate_order_sum(100,200,300)
calculate_order_sum(10,65)

Total Price:600
Total Price:75


### Function with keyword arguments (`**kwargs`)

Define a function `display_transaction_details` that takes a transaction ID and a variable number of keyword arguments (like `item`, `price`, `staff`). It should print all the details. Call this function with a transaction ID and a few key-value pairs.

In [82]:
def display_transaction_details(transaction_id,**kwargs):
    print(f"transaction id:{transaction_id}")
    for key,values in kwargs.items():
        print(f"{key}:{values}")
#calling the function
display_transaction_details(101, item="Chocolate", price=150,staff="Anjali")

transaction id:101
item:Chocolate
price:150
staff:Anjali


### Combining `*args` and `**kwargs`

Create a function `process_new_order` that takes `customer_name` as a positional argument, a variable number of items as `*args`, and additional order details as `**kwargs` (e.g., `payment_method`). Print all the information nicely.

In [30]:
def process_new_order(customer_name,*args,**kwargs):
    print(f"customer_name={customer_name}")
    print("Items")
    for items in args:
        print(f"Items={items}")
    print("Order_details")
    for key,values in kwargs.items():
        print(f"{key}:{values}")
#Calling the functions
process_new_order("Fahimida","Vanilla","Butterscotch",price=400,payment_method="UPI")

customer_name=Fahimida
Items
Items=Vanilla
Items=Butterscotch
Order_details
price:400
payment_method:UPI


## 5. Data Structures in Python

Data structures are fundamental for organizing and storing data efficiently. These problems will explore how to use Python's built-in data structures—lists, sets, tuples, and dictionaries—to manage various types of information, from inventory to customer orders.

### Simple range

Print the numbers from 0 to 4 using a `for` loop and `range()`.

In [31]:
for i in range(5):
    print(i)

0
1
2
3
4


### Range with a starting point

Simulate a countdown from 5 to 1. Print the numbers using a `for` loop with `range()`.

In [36]:
for i in range(5,0,-1):
    print(i)

5
4
3
2
1


### Range with step size

Print every other number from 1 to 10 (i.e., 1, 3, 5, ...).

In [37]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


### Iterating a list by index

You have a list of weekly expenses: `[5000, 4800, 5500]`. Use `range()` to loop through the list by index and print each expense with its corresponding week number (e.g., "Week 1: 5000 INR").

In [45]:
expenses=[5000,4800,5500]
for i in range(len(expenses)):
    print(f"Week number {i+1},{expenses[i]}INR")

Week number 1,5000INR
Week number 2,4800INR
Week number 3,5500INR


### Reverse range

Use `range()` to print numbers from 10 down to 1.

In [38]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


### Summing numbers in a range

Calculate the sum of all numbers from 1 to 100. Print the result.

In [48]:
del sum
total_sum=sum(range(1,101))
print(total_sum)

5050


### Range and `if` condition

Print all even numbers from 2 to 20 using `range()` and an `if` condition.

In [42]:
for i in range(2,20):
    if i%2==0:
        print(i)

2
4
6
8
10
12
14
16
18


### Looping to create a list

Create an empty list called `order_numbers`. Use a `for` loop and `range()` to add the first 5 order numbers (101, 102, 103, 104, 105) to this list.

In [51]:
order_numbers=[]
for i in range(101,106):
    order_numbers.append(i)
print(order_numbers)

[101, 102, 103, 104, 105]


### Range with two lists

You have two lists: `products = ['Vanilla', 'Chocolate']` and `prices = [100, 110]`. Use `range()` with the length of one of the lists to print each product and its price on a separate line.

In [59]:
products=['Vanilla','Chocolate']
prices=[100,110]
for i in range(len(products)):
    print(products[i],prices[i])

Vanilla 100
Chocolate 110


### Negative step size with range

Print the odd numbers from 9 down to 1.

In [49]:
for i in range(9,0,-2):
    print(i)

9
7
5
3
1


### Looping a fixed number of times for input

Ask the user to enter 3 new employee names. Use a `for` loop with `range()` to get the names and store them in a list.

In [69]:
employee_names=[]
for i in range(3):
    names=input("Enter employees name")
    employee_names.append(names)
print(f"Employees names:{employee_names}")

Enter employees name Fahimida
Enter employees name Tharuni
Enter employees name Akhila


Employees names:['Fahimida', 'Tharuni', 'Akhila']


### Using `range` to populate a dictionary

Create a dictionary to hold daily sales targets for 5 days. Use a `for` loop with `range()` to initialize the dictionary with keys `Day 1` through `Day 5` and a default value of `10000` for each.

In [70]:
sales={}
for day in range(5):
    sales[f"Day{day}"]=10000
print(sales)

{'Day0': 10000, 'Day1': 10000, 'Day2': 10000, 'Day3': 10000, 'Day4': 10000}


### Finding a factorial using a loop and range

Calculate the factorial of 5 (5!) using a loop and `range()`. The factorial of 5 is `5 * 4 * 3 * 2 * 1`. Print the result.

In [65]:
fact=1
n=5
for i in range(1,n+1):
    fact*=i
print(f"factorail of {n} is:{fact}")
            

factorail of 5 is:120


### Nested loops with range

Print a simple 3x3 grid of asterisks (`*`) using nested `for` loops and `range()`. The outer loop should control rows, and the inner loop should control columns.

In [74]:
for i in range(3):
    for j in range(3):
        print("*",end="")
    print()

***
***
***


### Range with a `while` loop

Use a `while` loop to print numbers from 0 to 4. Do not use a `for` loop for this problem. This is a practice to show the flexibility of loop structures.

In [77]:
n=0
while n<5:
    print(n)
    n+=1
    

0
1
2
3
4
